version: "3.8"

services:
  jenkins:
    image: jenkins-server
    build: ./jenkins/
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - sonarqube
    entrypoint: ["/usr/local/bin/retrieve_token.sh"]

  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  jenkins_home:
  postgres_data:
  sonarqube_conf:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
