jenkins:
  systemMessage: "Jenkins configured automatically by JCasC"

  authorizationStrategy:
    unsecured: {}
  globalNodeProperties:
    - envVars:
        env:
          - key: SONARQUBE_TOKEN
            value: "${SONARQUBE_TOKEN}"

tool:
  maven:
    installations:
      - name: "maven3"
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.8.4"

unclassified:
  location:
    url: http://localhost:8080

  sonarGlobalConfiguration:
    buildWrapperEnabled: true
    installations:
      - name: "SonarQube"
        serverUrl: "http://sonarqube:9000"
        credentialsId: ""

jobs:
  - script: >
      pipelineJob('java-app') {
          definition {
              cps {
                  script("""
                      pipeline {
                          agent any

                          environment {
                              SONARQUBE_SERVER = 'SonarQube'
                              SONARQUBE_URL = 'http://localhost:9000'
                              SONARQUBE_USER = 'admin'
                              SONARQUBE_PASSWORD = 'admin'
                          }

                          stages {
                              stage('Load Environment Variable') {
                                  steps {
                                      script {
                                          def envVars = readFile('/var/jenkins_home/sonarqube_token.env').trim().split('=')
                                          def token = envVars[1]
                                          env.SONARQUBE_TOKEN = token
                                          echo "Loaded SonarQube Token"
                                      }
                                  }
                              }

                              stage('Check-out') {
                                  steps {
                                      echo 'THIS IS MY AUTHENTICATION TOKEN'
                                      echo "${env.SONARQUBE_TOKEN}"
                                      echo 'Cloning repository'
                                      git 'https://github.com/shashirajraja/onlinebookstore.git'
                                  }
                              }

                              stage('Build') {
                                  steps {
                                      echo 'Building project with Maven...'
                                      withMaven(maven: 'maven3') {
                                          sh 'mvn clean install'
                                      }
                                  }
                              }

                              stage('SAST Analysis') {
                                  steps {
                                      echo 'Running SonarQube analysis...'
                                      withSonarQubeEnv('SonarQube') {
                                          sh "mvn sonar:sonar -Dsonar.login=${env.SONARQUBE_TOKEN}"
                                      }
                                  }
                              }

                              stage('Quality Gate') {
                                  steps {
                                      script {
                                          def qg = waitForQualityGate()
                                          if (qg.status != 'OK') {
                                              error "Pipeline aborted due to the quality gate failure: ${qg.status}"
                                          }
                                      }
                                  }
                              }

                              stage('Archive') {
                                  steps {
                                      echo 'Archiving artifacts...'
                                      archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
                                  }
                              }

                              stage('Notify') {
                                  steps {
                                      echo 'Sending notification...'
                                  }
                              }
                          }

                          post {
                              failure {
                                  echo 'Build failed, sending notification...'
                              }
                          }
                      }
                  """.stripIndent())
                  sandbox()
              }
          }
      }
