pipeline {
    agent any

    environment {
        SONARQUBE_SERVER = 'sonarqube'
    }

    stages {
        stage ('Check-out') {
            steps {
                echo ('Cloning repository')
                git 'https://github.com/shashirajraja/onlinebookstore.git'
            }
        }

        stage ('Build') {
            steps {
                echo ('Building project with Maven...')
                withMaven {
                    sh 'mvn compile'
                }
            }
        }

        stage ('SAST Analysis') {
            steps {
                echo ('Running SonarQube analysis...')
                withSonarQubeEnv('sonarqube') {
                    sh 'mvn sonar:sonar'
                }
            }
        }
    }
}